### ISSUE TITLE
Ncell removed the support for the old Ncell app (3.0.0.1)

### ISSUE THREAD

**Issue by hemantapkh** [hemantapkh/ncellapp#5]
Ncell removed the support for the old Ncell app (3.0.0.1) and hence the wrapper is not working anymore. 

**Update coming soon.**

**Comment by AdiC0DER** [comment]
cool i would love to see update

**Comment by hemantapkh** [comment]
I already pushed the code in the [development](https://github.com/hemantapkh/ncellapp/tree/development-2.0) branch.

Maybe I will see the website after releasing v2.

**Comment by hemantapkh** [comment]
v2.0.0 is released 🥳🎉
