### ISSUE TITLE
Functions not working as intended

### ISSUE THREAD

**Issue by rohitjoshi21** [hemantapkh/ncellapp#7]
I registered my number, got the OTP, validate the OTP and got the token. Then, I tried to check the balance in the given in the README file. I checked its content as mentioned in the guide but didn't get correct data.
It showed this:
`{'queryBalanceResponse': {'smsBalanceList': [], 'dataBalanceList': [{'uom': 'MB', 'balance': '18.77', 'ncellProductCode': '57925', 'usageInPercentage': 0.0, 'initialAmount': '200', 'accName': '100MB_Happy Spend_4G', 'ncellName': '100MB_Happy Spend_4G', 'tag': None, 'productName': None, 'expDate': 'Dec 11 2020 14:59:55'}, {'uom': 'MB', 'balance': '99.99', 'ncellProductCode': '57740', 'usageInPercentage': 0.0, 'initialAmount': '200', 'accName': '100MB_Happy Spend_All', 'ncellName': '100MB_Happy Spend_All', 'tag': None, 'productName': None, 'expDate': 'Dec 11 2020 14:59:55'}], 'creditBalanceDetail': {'expiryDate': 'Jul 25 2021 23:59:59', 'freeSmsCount': 10, 'tariffPlanRateOffNet': 0.0, 'balance': 0.00395343, 'unBilledAmount': 0.0, 'tariffPlanName': None, 'lastRechargeDate': 'Feb 03 2021 07:43:32', 'loanAmount': 0.0, 'creditUom': 'Rs.', 'tariffPlanRateOnNet': 0.0}, 'msisdn': '9803431968', 'voiceBalanceList': [], 'paidMode': 'Prepaid'}}`

Then, I checked this for another number and still got the same result as above. Also, I also couldn't send free sms by following the steps shown in the guide. Hope this issue is solved.

**Comment by hemantapkh** [comment]
I just checked and everything you mentioned worked fine for me. Regarding the incorrect data, I think you got confused because `balance()` returns different types of balance like SMS balance, data balance, main balance, etc. According to the response, your main balance is `0.00395343`, is that correct?

**Comment by hemantapkh** [comment]
Also, can you send the responseHeader and content of the free SMS?

**Comment by rohitjoshi21** [comment]
No, the balance data shown there is not incorrect. Maybe I have
done something wrong in my side. I will check once again and let you know.

**Comment by hemantapkh** [comment]
Any updates? If the error was from your side you can close the issue.

**Comment by rohitjoshi21** [comment]
Sorry, I haven't checked further. I am busy for some day. I will check and
close the issue asap.
